[package]
name = "paseto-dontuseme"
version = "0.1.0"
edition = "2021"

[dependencies]
rand_core = { version = "0.6", features = ["getrandom"] }

[dev-dependencies]
hex = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
